---
- name: Gather list of k3s hosts
  ansible.builtin.add_host:
    name: "{{ item }}"
    ansible_host: "{{ hostvars[item].ansible_host }}"
  loop: "{{ groups['k3s'] }}"
  run_once: true

- name: Add all entries to hosts file
  ansible.builtin.lineinfile:
    path: "{{ hosts_path }}"
    line: "{{ item.ansible_host }} {{ item.inventory_hostname }}"
    state: present
  loop: "{{ groups['k3s'] | map('extract', hostvars) }}"
  when: "'k3s' in group_names"

- name: Gather list of lb and master hosts
  ansible.builtin.add_host:
    name: "{{ item }}"
    ansible_host: "{{ hostvars[item].ansible_host }}"
  loop: "{{ groups['master'] + groups['lb'] }}"
  run_once: true

- name: Add all entries to hosts file
  ansible.builtin.lineinfile:
    path: "{{ hosts_path }}"
    line: "{{ item.ansible_host }} {{ item.inventory_hostname }}"
    state: present
  loop: > 
    {{ groups['master'] | map('extract', hostvars) | list 
    + groups['lb'] | map('extract', hostvars) | list }}
  when: "'lb' in group_names"