---
- name: Add DNS servers to resolv.conf
  ansible.builtin.lineinfile:
    path: "{{ resolv_conf_path }}"
    line: "{{ item.server }} {{ item.ip }}"
    state: present
  loop: "{{ dns_servers }}"

- name: Enable net.ipv4.ip_forward
  ansible.builtin.command: sudo sed -i 's;#net.ipv4.ip_forward=1;net.ipv4.ip_forward=1;' {{ sysctl_conf_path }}